// Code generated by "sloth "; DO NOT EDIT.

package unit1


func (i *IntSliceHeader) SetData(val []int) {
	i.Data = val
	//i.Update("data",val)
}

func (i *IntSliceHeader) SetLen(val int) {
	i.Len = val
	//i.Update("len",val)
}

func (i *IntSliceHeader) SetCap(val int) {
	i.Cap = val
	//i.Update("cap",val)
}
